import React from 'react';

export const theme = {
  bg: '#1e1e2e',
  card: '#2a2a3c',
  textMain: '#ffffff',
  textSec: '#a1a1aa',
  accentGreen: '#10b981',
  accentYellow: '#f59e0b',
  accentRed: '#ef4444',
  border: '#3f3f46',
  hover: '#3f3f46',
};

export const styles: Record<
  string,
  React.CSSProperties & { WebkitAppRegion?: 'drag' | 'no-drag' }
> = {
  container: {
    backgroundColor: theme.bg,
    color: theme.textMain,
    height: '100vh',
    fontFamily: '"Inter", system-ui, -apple-system, sans-serif',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    userSelect: 'none',
  },
  header: {
    padding: '16px 20px',
    borderBottom: `1px solid ${theme.border}`,
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    backgroundColor: theme.bg,
    zIndex: 10,
    WebkitAppRegion: 'drag' as const,
    cursor: 'default',
  },
  headerTitle: {
    fontSize: '18px',
    fontWeight: 700,
    margin: 0,
    letterSpacing: '-0.02em',
  },
  statusDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: theme.accentGreen,
    boxShadow: `0 0 8px ${theme.accentGreen}`,
  },
  scrollArea: {
    flex: 1,
    overflowY: 'auto',
    padding: '20px',
  },
  contentContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  card: {
    backgroundColor: theme.card,
    borderRadius: '12px',
    padding: '16px',
    boxShadow:
      '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
  },
  providerName: {
    fontSize: '16px',
    fontWeight: 600,
  },
  usageItem: {},
  usageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '6px',
    fontSize: '13px',
    color: theme.textSec,
  },
  progressTrack: {
    height: '8px',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: '4px',
    overflow: 'hidden',
    marginBottom: '6px',
  },
  progressBar: {
    height: '100%',
    borderRadius: '4px',
    transition: 'width 0.5s ease, background-color 0.3s ease',
  },
  metaRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '11px',
    color: theme.textSec,
  },
  resetTime: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  badge: {
    padding: '2px 8px',
    borderRadius: '10px',
    fontSize: '11px',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  bottomBar: {
    padding: '16px 20px',
    borderTop: `1px solid ${theme.border}`,
    backgroundColor: theme.card,
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
  },
  button: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    padding: '10px',
    borderRadius: '8px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 500,
    transition: 'all 0.2s',
  },
  // New Styles for Settings
  settingsSection: {
    marginBottom: '24px',
  },
  sectionTitle: {
    fontSize: '12px',
    fontWeight: 600,
    color: theme.textSec,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: '12px',
    paddingLeft: '4px',
  },
  settingRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
    backgroundColor: theme.card,
    borderRadius: '8px',
    marginBottom: '8px',
  },
  settingLabel: {
    fontSize: '14px',
    fontWeight: 500,
  },
  backButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'none',
    border: 'none',
    color: theme.textMain,
    cursor: 'pointer',
    padding: '4px',
    marginRight: '8px',
    borderRadius: '4px',
    WebkitAppRegion: 'no-drag' as const,
  },
  connectBtn: {
    padding: '6px 12px',
    borderRadius: '6px',
    border: 'none',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: '12px',
    backgroundColor: theme.accentGreen,
    color: '#000',
  },
  reconnectBtn: {
    padding: '6px 12px',
    borderRadius: '6px',
    border: `1px solid ${theme.border}`,
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: '12px',
    backgroundColor: 'transparent',
    color: theme.textSec,
  },
  checkbox: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
    accentColor: theme.accentGreen,
  },
  setupCard: {
    backgroundColor: theme.card,
    borderRadius: '12px',
    padding: '32px 20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    gap: '16px',
    border: `1px dashed ${theme.border}`,
  },
  setupBtn: {
    padding: '8px 20px',
    backgroundColor: theme.accentGreen,
    color: '#000',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: '13px',
  },
};
