import React from 'react';

export const getTheme = (glassMode: boolean) => ({
  bg: glassMode ? 'rgba(15, 15, 20, 0.7)' : '#1e1e2e',
  card: glassMode ? 'rgba(30, 30, 45, 0.9)' : '#2a2a3c',
  textMain: '#ffffff',
  textSec: '#a1a1aa',
  accentGreen: '#10b981',
  accentYellow: '#f59e0b',
  accentRed: '#ef4444',
  border: glassMode ? 'rgba(255, 255, 255, 0.1)' : '#3f3f46',
  hover: 'rgba(255, 255, 255, 0.05)',
  glassBg: 'rgba(255, 255, 255, 0.05)',
  glassBorder: glassMode ? 'rgba(255, 255, 255, 0.2)' : '#3f3f46',
  glassShadow: glassMode ? '0 8px 32px 0 rgba(0, 0, 0, 0.37)' : 'none',
  blur: glassMode ? 'blur(100px)' : 'none',
  textShadow: glassMode ? '0 1px 3px rgba(0, 0, 0, 0.8)' : 'none',
});

// For backward compatibility or default usage
export const theme = getTheme(true);

export const getStyles = (
  glassMode: boolean
): Record<
  string,
  React.CSSProperties & { WebkitAppRegion?: 'drag' | 'no-drag' }
> => {
  const t = getTheme(glassMode);

  return {
    container: {
      backgroundColor: t.bg,
      backdropFilter: t.blur,
      WebkitBackdropFilter: t.blur,
      color: t.textMain,
      height: '100vh',
      fontFamily: '"Inter", system-ui, -apple-system, sans-serif',
      display: 'flex',
      flexDirection: 'column',
      overflow: 'hidden',
      userSelect: 'none',
    },
    header: {
      padding: '16px 20px',
      borderBottom: '1px solid ' + t.glassBorder,
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
      backgroundColor: t.bg,
      backdropFilter: t.blur,
      WebkitBackdropFilter: t.blur,
      zIndex: 10,
      WebkitAppRegion: 'drag' as const,
      cursor: 'default',
    },
    headerTitle: {
      fontSize: '18px',
      fontWeight: 700,
      margin: 0,
      letterSpacing: '-0.02em',
      textShadow: t.textShadow,
    },
    statusDot: {
      width: '8px',
      height: '8px',
      borderRadius: '50%',
      backgroundColor: t.accentGreen,
      boxShadow: `0 0 8px ${t.accentGreen}`,
    },
    scrollArea: {
      flex: 1,
      overflowY: 'auto',
      padding: '20px',
    },
    contentContainer: {
      display: 'flex',
      flexDirection: 'column',
      gap: '16px',
    },
    card: {
      backgroundColor: t.card,
      backdropFilter: t.blur,
      WebkitBackdropFilter: t.blur,
      border: '1px solid ' + t.glassBorder,
      borderRadius: '12px',
      padding: '16px',
      boxShadow: t.glassShadow,
    },
    cardHeader: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: '16px',
    },
    providerName: {
      fontSize: '16px',
      fontWeight: 600,
      textShadow: t.textShadow,
    },
    usageItem: {},
    usageHeader: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: '6px',
      fontSize: '13px',
      color: t.textSec,
      textShadow: t.textShadow,
    },
    progressTrack: {
      height: '8px',
      backgroundColor: 'rgba(255,255,255,0.1)',
      borderRadius: '4px',
      overflow: 'hidden',
      marginBottom: '6px',
    },
    progressBar: {
      height: '100%',
      borderRadius: '4px',
      transition: 'width 0.5s ease, background-color 0.3s ease',
    },
    metaRow: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      fontSize: '11px',
      color: t.textSec,
    },
    resetTime: {
      display: 'flex',
      alignItems: 'center',
      gap: '4px',
    },
    badge: {
      padding: '2px 8px',
      borderRadius: '10px',
      fontSize: '11px',
      fontWeight: 600,
      display: 'flex',
      alignItems: 'center',
      gap: '4px',
    },
    settingsSection: {
      marginBottom: '24px',
    },
    sectionTitle: {
      fontSize: '12px',
      fontWeight: 600,
      color: t.textSec,
      textTransform: 'uppercase',
      letterSpacing: '0.05em',
      marginBottom: '12px',
      paddingLeft: '4px',
      textShadow: t.textShadow,
    },
    settingRow: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '12px 16px',
      backgroundColor: t.card,
      backdropFilter: t.blur,
      WebkitBackdropFilter: t.blur,
      border: '1px solid ' + t.glassBorder,
      borderRadius: '8px',
      marginBottom: '8px',
    },
    settingLabel: {
      fontSize: '14px',
      fontWeight: 500,
      textShadow: t.textShadow,
    },
    backButton: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: 'none',
      border: 'none',
      color: t.textMain,
      cursor: 'pointer',
      padding: '4px',
      marginRight: '8px',
      borderRadius: '4px',
      WebkitAppRegion: 'no-drag' as const,
    },
    connectBtn: {
      padding: '6px 12px',
      borderRadius: '6px',
      border: 'none',
      cursor: 'pointer',
      fontWeight: 600,
      fontSize: '12px',
      backgroundColor: t.accentGreen,
      color: '#000',
    },
    reconnectBtn: {
      padding: '6px 12px',
      borderRadius: '6px',
      border: `1px solid ${t.border}`,
      cursor: 'pointer',
      fontWeight: 600,
      fontSize: '12px',
      backgroundColor: 'transparent',
      color: t.textSec,
    },
    checkbox: {
      width: '18px',
      height: '18px',
      cursor: 'pointer',
      accentColor: t.accentGreen,
    },
    setupCard: {
      backgroundColor: t.card,
      backdropFilter: t.blur,
      WebkitBackdropFilter: t.blur,
      border: '1px solid ' + t.glassBorder,
      borderRadius: '12px',
      padding: '32px 20px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      textAlign: 'center',
      gap: '16px',
      boxShadow: t.glassShadow,
    },
    setupBtn: {
      padding: '8px 20px',
      backgroundColor: t.accentGreen,
      color: '#000',
      border: 'none',
      borderRadius: '6px',
      cursor: 'pointer',
      fontWeight: 600,
      fontSize: '13px',
    },
  };
};

// For backward compatibility
export const styles = getStyles(true);
